### ISSUE TITLE
Wiring diagrams for bicategories of relations

### ISSUE THREAD

**Issue by jpfairbanks** [epatters/Catlab.jl#49]
I think this is a bug in v0.3.

MWE:
The following code returns a `MethodError: no method matching dagger(::WiringDiagram)`
```julia
X,Y = Ob(FreeBicategoryRelations, :X, :Y)
f = Hom(:f, X,Y)
to_wiring_diagram(f) #works
to_wiring_diagram(dagger(f)) #errors
```

Is this a real bug?

**Comment by epatters** [comment]
Probably a bug. I'll look into it soon.

**Comment by jpfairbanks** [comment]
Thanks, here is a related problem,

```julia
X,Y = Ob(FreeAbelianBicategoryRelations, :X, :Y)
f = Hom(:f, X,Y)
to_wiring_diagram(f)
wd(mplus(X))
``` 

`MethodError: no method matching mplus(::Ports{Symbol})`

**Comment by epatters** [comment]
Having refreshed myself on the situation, I'd say that these are not so much bugs as features that I never implemented. Bicategories of relations in Catlab have been neglected, since I'm not currently using them in any computational project. But I would like to improve this.

I see two different issues here:

1. Wiring diagrams for bicategories of relations: I need to implement the dagger and possibly a few other things. This should be straightforward, and I'll do it shortly.

2. Wiring diagrams for *abelian* bicategories of relations: the path here is less straightforward because there are conceptual problems, not just programming ones. As I discuss in the paper, string diagrams with multiple monoidal products seem to largely uncharted territory. I don't know how to proceed. It would be interesting to think about this, because bicategories of relations aren't the only place where multiple monoidal products naturally show up.

**Comment by epatters** [comment]
The first step is probably to resolve #54. Then we can make sure that all the operations in a bicategory of relations get properly translated into wiring diagrams.

**Comment by jpfairbanks** [comment]
For making WDs for Rel, should we introduce a `DaggerBox` that has an AbstractBox in it tells you to flip it? I am thinking like this:

```julia
struct DaggerBox{T} where T<: AbstractBox
  box::T
end

dagger(b::Box) == DaggerBox(b)
dagger(b::DaggerBox) = b.box
```

Do you think this is the right approach?

**Comment by epatters** [comment]
PR #68 is a start towards a proper implementation of wiring diagrams for bicategories of relations.

If I'm not mistaken, the dagger is now the only missing operation. I like the strategy suggested here. We would further write:

```julia
input_ports(box::DaggerBox) = output_ports(box.box)
output_ports(box::DaggerBox) = input_ports(box.box)
```

**Comment by epatters** [comment]
Issues related to abelian bicategories of relations will be taken up in #70.
