### ISSUE TITLE
Color conventions for multiple (co)diagonals

### ISSUE THREAD

**Issue by epatters** [epatters/Catlab.jl#79]
Time to bike-shed. In abelian bicategories of relations (#70), and in the closely related graphical linear algebra (#65), there are two sets of diagonals and codiagonals, one for copies/merges and one for addition/coaddition. In wiring diagrams, these are represented by junctions of different colors, usually black (filled) and white (unfilled).

What convention should be the default? Arguments in favor of black for copies, white for addition:

- Black, currently the default color for junctions, *always* means copying, regardless of context
- Used in Bonchi et al's paper on interacting Hopf algebras and in the GLA blog series

Arguments in favor of white for copies, black for addition:

- Node colors match the appearance of LaTeX textual syntax, as used by Selinger and others, e.g., $\Delta$ is always copying and a solid black triangle, or just +, is used for (co)addition
- Used in Baez & Erbele's paper "Categories in control"
- Used in my paper on bicategories of relations (for the two above reasons)

**Comment by jpfairbanks** [comment]
Oh this is really tough. I like black for copies, white for addition because I learned from GLA blog series. I don't think that the "matching the latex textual syntax" argument is important. I would not have put that together without being explicitly told. In the end, I don't think it matters that much since we will still have to announce the default when showing the diagrams.

If we had 3 diagonal/codiagonals, what would we do? Have them in different colors RGB? Do we need to have an implementation that lets you assign graphical elements to homs based on the type parameter of the `WiringDiagram`?

**Comment by epatters** [comment]
I agree that it is not too important in the end. I'm fine with using black for copies, white for addition. I like that in this case, black will always mean "copy", in or outside the GLA setting.

I guess we'd have to use RGB if there were three or more (co)diagonals. I actually don't know a situation where this happens. Do you? In any case, this is further argument for ensuring that it is possible override whatever defaults we settle on.

**Comment by jpfairbanks** [comment]
Nah I don't have an example, of a useful category with 3 codiagonals. I was just thinking that if we came up with a solution that worked for general n, then we can use that to inform the n=2 case. That would still leave a choice of default colors, so it wouldn't actually help. I like that black is always copy, since copy is special in the `@parse_wiring_diagram` syntax as variable access it makes sense to give copy first dibs on a color.

**Comment by epatters** [comment]
OK, I am in agreement. Let's go with that for now.
